/*
 * File: gridHistoriadeUsuario.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridHistoriadeUsuarioUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Historias de usuario',
    width: 400,
    height: 250,
    initComponent: function() {
        this.bbar = {
            xtype: 'paging',
            displayInfo: true
        };
        this.tbar = {
            xtype: 'grid16_toolbar'
        };
        this.columns = [
            {
                xtype: 'gridcolumn',
                header: 'id',
                dataIndex: 'id',
                sortable: true,
                width: 100
            },
            {
                xtype: 'gridcolumn',
                header: 'descripcion',
                dataIndex: 'descripcion',
                sortable: true,
                width: 100
            }
        ];
        gridHistoriadeUsuarioUi.superclass.initComponent.call(this);
    }
});
