/*
 * File: stoHistoriasDUsuario.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

stoHistoriasDUsuario = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        stoHistoriasDUsuario.superclass.constructor.call(this, Ext.apply({
            storeId: 'MyStore',
            root: 'datos',
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'descripcion'
                }
            ]
        }, cfg));
    }
});
Ext.reg('stoHistoriasDUsuario', stoHistoriasDUsuario);