/*
 * File: main_layout.js
 * Date: Wed Sep 05 2012 23:57:27 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

main_layout = Ext.extend(main_layoutUi, {
    initComponent: function() {
        main_layout.superclass.initComponent.call(this);
    }
});
Ext.reg('main_layout', main_layout);