/*
 * File: main_layout.ui.js
 * Date: Thu Sep 06 2012 00:29:42 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

main_layoutUi = Ext.extend(Ext.Panel, {
    width: 718,
    height: 250,
    layout: 'border',
    initComponent: function() {
        this.items = [
            {
                xtype: 'tabpanel',
                activeTab: 0,
                region: 'center',
                border: false,
                style: '',
                bodyStyle: 'border-style:solid;border-width:0 0 0 1px;',
                ref: 'tabPanel',
                items: [
                    {
                        xtype: 'panel',
                        title: 'Home'
                    }
                ]
            },
            {
                xtype: 'panel',
                region: 'west',
                width: 217,
                layout: 'accordion',
                activeItem: 2,
                split: true,
                collapsible: true,
                collapseMode: 'mini',
                hideCollapseTool: true,
                itemId: 'pnlAcordeon',
                hideBorders: true,
                border: false,
                style: 'border-style: sodli;border-width:0 1px 0 0;',
                ref: 'pnlAcordeon',
                items: [
                    {
                        xtype: 'panel',
                        title: 'Clientes',
                        bodyStyle: 'border-style:solid;border-width:0 0 1px 0;',
                        items: [
                            {
                                xtype: 'treepanel',
                                border: false,
                                root: {
                                    text: 'Tree Node'
                                },
                                loader: {

                                }
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Productos',
                        bodyStyle: 'border-style:solid;border-width:0 0 1px 0;',
                        items: [
                            {
                                xtype: 'treepanel',
                                border: false,
                                root: {
                                    text: 'Tree Node'
                                },
                                loader: {

                                }
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Facturacion',
                        border: false,
                        style: 'border-width: 0;',
                        bodyStyle: 'border-style:solid;border-width:0 0 1px 0;',
                        items: [
                            {
                                xtype: 'treepanel',
                                border: false,
                                root: {
                                    text: 'Tree Node'
                                },
                                loader: {
                                    url: '/menus/getMenus',
                                    baseParams: {
                                        padreId: 0
                                    }
                                }
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Sistema',
                        style: 'border-width:0;',
                        border: false,
                        bodyStyle: 'border-width:0;',
                        hideBorders: true,
                        items: [
                            {
                                xtype: 'treepanel',
                                border: false,
                                root: {
                                    text: 'Tree Node'
                                },
                                loader: {

                                }
                            }
                        ]
                    }
                ]
            }
        ];
        main_layoutUi.superclass.initComponent.call(this);
    }
});
