/*
 * File: main_layout.js
 * Date: Wed Sep 05 2012 23:57:27 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

main_layout = Ext.extend(main_layoutUi, {
    initComponent: function() {
        main_layout.superclass.initComponent.call(this);		
		
		this.configurarComportamientoMenu();
		
		Ext.apply(this.tabPanel, comportamiento_tab_manager);
		this.tabPanel.activarComportamiento();		
    },
	configurarComportamientoMenu:function(){
		/*
		Ext.apply(this.tabPanel, comportamiento_tree_menu);
		this.tabPanel.activarComportamientoTreeMenu();
		*/
		this.treeMenus.getRootNode().expand();		
		//this.treeSistema.getRootNode().expand();
		
		this.on('click',function(node, e){
			if (node.attributes != undefined){
				this.procesarClick(node.attributes);
			}			
		},this);
	},
	procesarClick:function(nodo){	
		if ( !Ext.isEmpty(nodo.xtype) ){
			var tab=this.tabPanel.add({
				xtype:nodo.xtype,
				closable:true,
				
			});			
			tab.show();
		}
	}
});
Ext.reg('main_layout', main_layout);