/*
 * File: gridModelo.ui.js
 * Date: Sun Aug 12 2012 21:12:49 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridModeloUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Listado',
    store: 'stoModelo',
    width: 449,
    height: 254,
    autoExpandColumn: 'colNombre',
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    iconCls: 'btnNuevo',
                    itemId: 'btnNuevo'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    iconCls: 'btnEliminar',
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'button',
                    text: 'Editar',
                    iconCls: 'btnEditar',
                    ref: '../btnEditar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    text: 'Switch',
                    iconCls: 'btnSwitch',
                    ref: '../btnSwitch'
                }
            ]
        };
        this.bbar = {
            xtype: 'paging',
            store: 'stoModelo'
        };
        this.columns = [
            {
                xtype: 'gridcolumn',
                header: 'uuid',
                dataIndex: 'uuid',
                sortable: true,
                width: 100
            },
            {
                xtype: 'gridcolumn',
                header: 'id',
                dataIndex: 'id',
                sortable: true,
                width: 100
            },
            {
                xtype: 'gridcolumn',
                header: 'nombre',
                dataIndex: 'nombre',
                sortable: true,
                width: 100,
                id: 'colNombre'
            }
        ];
        gridModeloUi.superclass.initComponent.call(this);
    }
});
