/*
 * File: gridTareas.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridTareasUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Lista de Tareas',
    initComponent: function() {
        this.bbar = {
            xtype: 'paging'
        };
        this.tbar = {
            ref: 'tbGridDetalle',
            xtype: 'grid16_toolbar'
        };
        this.columns = [
            {
                xtype: 'gridcolumn',
                header: 'id',
                dataIndex: 'id',
                sortable: true,
                width: 100
            },
            {
                xtype: 'gridcolumn',
                header: 'descripcion',
                dataIndex: 'descripcion',
                sortable: true,
                width: 100
            },
            {
                xtype: 'gridcolumn',
                header: 'dificultad',
                dataIndex: 'dificultad',
                sortable: true,
                width: 100
            },
            {
                xtype: 'gridcolumn',
                header: 'tiempo_estimado',
                dataIndex: 'tiempo_estimado',
                sortable: true,
                width: 100
            },
            {
                xtype: 'gridcolumn',
                header: 'estado',
                dataIndex: 'estado',
                sortable: true,
                width: 100
            },
            {
                xtype: 'gridcolumn',
                header: 'usuarioAsignado',
                dataIndex: 'usuarioAsignado',
                sortable: true,
                width: 100
            }
        ];
        gridTareasUi.superclass.initComponent.call(this);
    }
});
