/*
 * File: grid16_toolbar.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

grid16_toolbar = Ext.extend(grid16_toolbarUi, {
    initComponent: function() {
        grid16_toolbar.superclass.initComponent.call(this);
    }
});
Ext.reg('grid16_toolbar', grid16_toolbar);