/*
 * File: catMenus.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

catMenusUi = Ext.extend(Ext.Panel, {
    title: 'Catalogo de Menus',
    height: 458,
    layout: 'border',
    bodyStyle: '',
    initComponent: function() {
        this.items = [
            {
                xtype: 'panel',
                region: 'west',
                width: 500,
                split: true,
                collapseMode: 'mini',
                layout: 'fit',
                bodyStyle: 'border-width:0 1px 1px 0;',
                items: [
                    {
                        ref: '../treeMenus',
                        xtype: 'TreeGridMenu'
                    }
                ],
                bbar: {
                    xtype: 'toolbar',
                    style: 'border-width:1px 1px 0 0;',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            iconCls: 'x-tbar-loading',
                            ref: '../../btnRefresh'
                        }
                    ]
                }
            },
            {
                xtype: 'form',
                title: 'Edicion',
                bodyStyle: 'padding:8px;border-width:0 0px 0px 0px;',
                region: 'center',
                style: 'border-width:0 0px 0px 1px;',
                border: false,
                ref: 'frmEdicion',
                items: [
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Id',
                        anchor: '100%',
                        name: 'id',
                        disabled: true,
                        ref: '../txtId'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Nombre',
                        anchor: '100%',
                        name: 'nombre'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'xtype',
                        anchor: '100%',
                        name: 'xtype'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Icon',
                        anchor: '100%',
                        name: 'icon'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'Padre',
                        anchor: '100%',
                        name: 'padre',
                        ref: '../txtPadre'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: 'UUID',
                        anchor: '100%',
                        disabled: true,
                        name: 'UUID'
                    }
                ]
            }
        ];
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Guardar',
                    iconCls: 'btnGuardarIcon',
                    itemId: 'btnGuardar',
                    scale: 'medium',
                    arrowAlign: 'bottom',
                    iconAlign: 'top',
                    ref: '../btnGuardar'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    iconCls: 'btnEliminarIcon',
                    itemId: 'btnEliminar',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    iconCls: 'btnNuevoIcon',
                    itemId: 'btnNuevo',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnNuevo'
                },
                {
                    xtype: 'button',
                    text: 'Recargar',
                    iconCls: 'btnRecargarIcon',
                    itemId: 'btnRecargar',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnRecargar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    text: 'Switch',
                    iconCls: 'btnSwitchIcon',
                    itemId: 'btnSwitch',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnSwitch'
                }
            ]
        };
        catMenusUi.superclass.initComponent.call(this);
    }
});
