/*
 * File: TreeGridMenu.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

TreeGridMenu = Ext.extend(TreeGridMenuUi, {
    initComponent: function() {
        TreeGridMenu.superclass.initComponent.call(this);
    }
});
Ext.reg('TreeGridMenu', TreeGridMenu);