/*
 * File: TreeGridMenu.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

TreeGridMenuUi = Ext.extend(Ext.Panel, {
    width: 100,
    border: false,
    initComponent: function() {
        TreeGridMenuUi.superclass.initComponent.call(this);
    }
});
