/*
 * File: grid_tareas.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

grid_tareas = Ext.extend(grid_tareasUi, {
	xtype_del_form:'edicion_tareas',
	plugins:[CatGridPlugin],
    initComponent: function() {
        grid_tareas.superclass.initComponent.call(this);
		
		this.store=new stoTareas();
		alert("asd");
		
		this.store.on('beforeload',function(){
			console.log(this);
			this.store.baseParams.fk_historia=this.initialConfig.idHistoria;
		},this);
    }
});
Ext.reg('grid_tareas', grid_tareas);