/*
 * File: stoTareas.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

stoTareas = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        stoTareas.superclass.constructor.call(this, Ext.apply({
            storeId: 'MyStore',
            root: 'datos',
            url: '/tareas/listar',
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'descripcion'
                },
                {
                    name: 'prioridad'
                },
                {
                    name: 'fk_historia'
                },
                {
                    name: 'detalles'
                },
                {
                    name: 'fk_estado'
                },
                {
                    name: 'estimado'
                },
                {
                    name: 'duracion'
                }
            ]
        }, cfg));
    }
});
