/*
 * File: crud16_toolbar.js
 * Date: Thu Sep 13 2012 22:05:28 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

crud16_toolbar = Ext.extend(crud16_toolbarUi, {
    initComponent: function() {
        crud16_toolbar.superclass.initComponent.call(this);
    }
});
Ext.reg('mytoolbar', crud16_toolbar);