/*
 * File: frmTarea.js
 * Date: Thu Sep 13 2012 22:05:28 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

frmTarea = Ext.extend(frmTareaUi, {
    initComponent: function() {
        frmTarea.superclass.initComponent.call(this);
		//--------------------------------------
		this.txtId.setVisible(false);	
		//this.txtGrupo.setVisible(false);			
		//--------------------------------------
		this.on('activate',function(){
			if (this.cargado==undefined){
				this.txtFK_historia.setValue( this.MasterId );
			}		
		},this);
		
		Ext.applyIf(this,comportamiento_formulario);
		this.controlador='tareas';
		this.activarComportamiento();				
    },
	onNuevo:function(){
		
		this.txtFK_historia.setValue( this.MasterId );
	},
});
Ext.reg('frmTarea', frmTarea);