/*
 * File: frmTarea.ui.js
 * Date: Thu Sep 13 2012 23:03:23 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

frmTareaUi = Ext.extend(Ext.form.FormPanel, {
    title: 'My Form',
    width: 400,
    height: 250,
    padding: 10,
    initComponent: function() {
        this.tbar = {
            xtype: 'crud16_toolbar'
        };
        this.items = [
            {
                xtype: 'textfield',
                fieldLabel: 'Label',
                anchor: '100%',
                name: 'id',
                ref: 'txtId'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Label',
                anchor: '100%',
                name: 'descripcion',
                ref: 'txtDescripcion'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Label',
                anchor: '100%',
                name: 'fk_historia',
                ref: 'txtFK_historia'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Label',
                anchor: '100%'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Label',
                anchor: '100%'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Label',
                anchor: '100%'
            }
        ];
        frmTareaUi.superclass.initComponent.call(this);
    }
});
