/*
 * File: ScrumMod.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ScrumModUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Scrum',
    width: 400,
    height: 250,
    padding: 10,
    initComponent: function() {
        ScrumModUi.superclass.initComponent.call(this);
    }
});
