/*
 * File: ScrumMod.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

ScrumMod = Ext.extend(ScrumModUi, {
    initComponent: function() {
        ScrumMod.superclass.initComponent.call(this);
    }
});
Ext.reg('ScrumMod', ScrumMod);