/*
 * File: Scrum.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ScrumUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Scrum',
    width: 400,
    height: 250,
    padding: 10,
    initComponent: function() {
        this.items = [
            {
                xtype: 'combo',
                valueField: 'id',
                displayField: 'nombre',
                minChars: 0,
                triggerAction: 'all',
                itemId: 'cmbProyectos',
                emptyText: 'cargando proyectos...',
                fieldLabel: 'Seleccione',
                autoSelect: false,
                ref: 'cmbProyectos'
            }
        ];
        ScrumUi.superclass.initComponent.call(this);
    }
});
