/*
 * File: gridSprints.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridSprintsUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Lista  de proyectos',
    width: 400,
    height: 250,
    initComponent: function() {
        this.columns = [
            {
                xtype: 'gridcolumn',
                header: 'nombre',
                dataIndex: 'nombre',
                sortable: true,
                width: 300
            }
        ];
        this.bbar = {
            xtype: 'paging',
            displayInfo: true
        };
        this.tbar = {
            xtype: 'grid16_toolbar'
        };
        gridSprintsUi.superclass.initComponent.call(this);
    }
});
