/*
 * File: edicion_tareas.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

edicion_tareasUi = Ext.extend(Ext.form.FormPanel, {
    padding: 10,
    autoScroll: true,
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Guardar',
                    iconCls: 'btnGuardarIcon_16',
                    itemId: 'btnGuardar',
                    arrowAlign: 'bottom',
                    ref: '../btnGuardar'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    iconCls: 'btnEliminarIcon_16',
                    itemId: 'btnEliminar',
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    iconCls: 'btnNuevoIcon_16',
                    itemId: 'btnNuevo',
                    ref: '../btnNuevo'
                },
                {
                    xtype: 'button',
                    text: 'Recargar',
                    iconCls: 'btnRecargarIcon_16',
                    itemId: 'btnRecargar',
                    ref: '../btnRecargar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'label',
                    text: 'Estado:'
                },
                {
                    xtype: 'tbspacer',
                    width: 10
                },
                {
                    xtype: 'combo',
                    displayField: 'nombre',
                    valueField: 'id',
                    minChars: 0,
                    triggerAction: 'all',
                    tpl: [
                        '<tpl for="."><div class="x-combo-list-item" style="clear:both"><div class="scrum_estado_id_{id}" style="float:left;"></div><div style="float:left; margin-left:10px;">{nombre}</div></div>',
                        '</tpl>'
                    ],
                    ref: '../cmbEstado'
                },
                {
                    xtype: 'tbspacer',
                    width: 10
                },
                {
                    xtype: 'tbfill'
                }
            ]
        };
        this.items = [
            {
                xtype: 'textfield',
                fieldLabel: 'Id',
                anchor: '100%',
                name: 'id',
                ref: 'txtId'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Tarea',
                anchor: '100%',
                name: 'descripcion',
                ref: 'txtDescripcion'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Historia',
                anchor: '100%',
                name: 'fk_historia',
                ref: 'txtHistoria'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Estimado',
                anchor: '100%',
                name: 'estimado',
                hidden: true,
                hideLabel: true,
                ref: 'txtEstimado'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Duracion',
                name: 'duracion',
                width: 150,
                hidden: true,
                hideLabel: true
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Prioridad',
                name: 'prioridad',
                width: 150
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Estado',
                name: 'fk_estado',
                ref: 'txtEstado'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Label',
                anchor: '100%',
                name: 'nombreEstado',
                ref: 'txtNombreEstado'
            },
            {
                xtype: 'textarea',
                anchor: '100%',
                fieldLabel: 'Como probarlo',
                name: 'como_probarlo',
                height: 200
            },
            {
                xtype: 'htmleditor',
                fieldLabel: 'Notas',
                anchor: '100%',
                height: 400,
                name: 'detalles'
            }
        ];
        edicion_tareasUi.superclass.initComponent.call(this);
    }
});
