/*
 * File: edicion_tareas.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

edicion_tareas = Ext.extend(edicion_tareasUi, {
	
    initComponent: function() {
        edicion_tareas.superclass.initComponent.call(this);
		this.txtId.setVisible(false);
		this.iconCls=Ext.ux.TDGi.iconMgr.getIcon('/imagenes/Human-O2/16x16/actions/gtk-preferences.png');
		this.txtHistoria.setVisible(false);		
		this.txtEstado.setVisible(false);
		this.txtNombreEstado.setVisible(false);
		
		this.controlador='tareas';
		
		
		Ext.applyIf(this,comportamiento_formulario);		
		this.activarComportamiento();			
		
		this.cmbEstado.store=new stoEstadoHistoria();
		this.cmbEstado.on('select',function( combo, record, index){
			this.txtEstado.setValue(record.id);
		},this);
		
		this.cmbEstado.on('cargado',function( combo, record, index){		
			//No nos confiamos en si el combo ya tiene los datos, por estandar, se carga tambien el valor a mostrar, en este caso, nombreEstado											
			var estado={
				id:this.txtEstado.getValue(),
				nombre:this.txtNombreEstado.getValue()
			};
			this.cmbEstado.store.loadData({datos:estado});
			this.cmbEstado.setValue(estado.id);			
		},this);		
		this.cmbEstado.store.load();
				
		this.on('guardado',function(){			
			this.cargarCombos();
		},this);
				
		this.on('cargado',function(){	
			var id=this.txtId.getValue();
			if (id==''){
				id=0;
			}			
			
			if (id==0 ){				
				var fk_historia=this.initialConfig.fk_historia;
				if ( fk_historia!=undefined){
					this.txtHistoria.setValue(fk_historia);					
				}
				
			}
			this.cargarCombos();
		},this);
    },
	cargarCombos:function(){
		var estado={
			id:this.txtEstado.getValue(),
			nombre:this.txtNombreEstado.getValue()
		};
		
		this.cmbEstado.store.loadData({datos:estado});
		this.cmbEstado.setValue(estado.id);
	},	
	
	actualizarTitulo:function(	action ){
		if (action=="guardado" || action=="edicion")
			this.setTitle(this.txtDescripcion.getValue() );
	}
});
Ext.reg('edicion_tareas', edicion_tareas);