/*
 * File: frmProyecto.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

frmProyectoUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Edicion',
    width: 400,
    padding: 10,
    initComponent: function() {
        this.items = [
            {
                xtype: 'textfield',
                fieldLabel: 'Id',
                anchor: '100%',
                name: 'id',
                hidden: true,
                hideLabel: true,
                ref: 'txtId'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Nombre Publico',
                name: 'nombre',
                ref: 'txtNombre'
            },
            {
                xtype: 'htmleditor',
                anchor: '100%',
                fieldLabel: 'Descripción',
                name: 'descripcion'
            }
        ];
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Guardar',
                    iconCls: 'btnGuardarIcon_16',
                    itemId: 'btnGuardar',
                    arrowAlign: 'bottom',
                    ref: '../btnGuardar'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    iconCls: 'btnEliminarIcon_16',
                    itemId: 'btnEliminar',
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    iconCls: 'btnNuevoIcon_16',
                    itemId: 'btnNuevo',
                    ref: '../btnNuevo'
                },
                {
                    xtype: 'button',
                    text: 'Recargar',
                    iconCls: 'btnRecargarIcon_16',
                    itemId: 'btnRecargar',
                    ref: '../btnRecargar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'tbfill'
                }
            ]
        };
        frmProyectoUi.superclass.initComponent.call(this);
    }
});
