/*
 * File: frmProyecto.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

frmProyectoUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Edicion',
    width: 400,
    padding: 10,
    initComponent: function() {
        this.items = [
            {
                xtype: 'textfield',
                fieldLabel: 'Id',
                anchor: '100%',
                name: 'id',
                ref: 'txtId'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Nombre Publico',
                name: 'nombre',
                ref: 'txtNombre'
            },
            {
                xtype: 'htmleditor',
                anchor: '100%',
                fieldLabel: 'Label',
                name: 'descripcion'
            }
        ];
        this.tbar = {
            ref: 'tbCrud',
            xtype: 'crud16_toolbar'
        };
        frmProyectoUi.superclass.initComponent.call(this);
    }
});
