/*
 * File: catHistoria.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

catHistoria = Ext.extend(catHistoriaUi, {
	actualizarTitulo:function(	action ){
	},
    initComponent: function() {
        catHistoria.superclass.initComponent.call(this);
		
		this.txtId.setVisible(false);
		this.txtPadre.setVisible(false);
		this.txtProyecto.setVisible(false);
		
		this.arbolGrid.on('click',function(node, e){			
			if (node.attributes != undefined){
				this.txtId.setValue(node.attributes.id);
				this.recargar();
			}
		},this);
		
		this.arbolGrid.loader.on('load',function(){
			var root=this.arbolGrid.getRootNode();
			root.expand(true);
		},this);
		
		this.controlador='historias';
		Ext.applyIf(this,comportamiento_formulario);
		this.activarComportamiento();
		
		var form=this.getForm();
		form.on("actioncomplete",function(form, action){
			if (action.type!='load'){
				this.recargarArbol();
			}
		},this);
		
		this.on('eliminado',this.recargarArbol,this);
		//form.on("actioncomplete",this.recargarArbol,this);
		//form.on("actioncomplete",this.recargarArbol,this);
		this.btnRefresh.on('click',this.recargarArbol,this);
		
		if (this.btnRefresh!=undefined){			
			this.btnRefresh.on('click',this.recargarArbol,this);
		}
		
		this.cmbProyectos.store= new  stoProyectos();
		
		var loader=this.arbolGrid.loader;
		loader.on("beforeload", function(treeLoader, node) {
			if (this.baseParams == undefined) this.baseParams={};
			loader.baseParams.proyecto_id = this.arbolGrid.proyectoId || 0;			
		}, this);
		
		 
		 
		this.cmbProyectos.on('select',function(combo, record, index){
			this.arbolGrid.proyectoId= record.data.id;
			
			var root = this.arbolGrid.getRootNode();
			root.setText(record.data.nombre);
			this.recargarArbol();
			
		},this);
		
		this.recargarArbol();
		
    },
	recargarArbol:function(){
		var arbol=this.arbolGrid;
		var root=arbol.getRootNode();
		var loader=arbol.loader;
		loader.load(root);		
	},	
	onNuevo:function(){
		var selMod=this.arbolGrid.getSelectionModel();
		var node = selMod.getSelectedNode();
		this.txtProyecto.setValue( this.cmbProyectos.getValue() );
		if (node==undefined) {
			this.txtPadre.setValue( 1 );
		}else{
			this.txtPadre.setValue(node.attributes.id);
			
		}
		
		
	},
	getForm:function(){
		return this.frmEdicion.getForm();
	}	
});
Ext.reg('catHistoria', catHistoria);