/*
 * File: catHistoria.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

catHistoria = Ext.extend(catHistoriaUi, {
	actualizarTitulo:function(	action ){
	},
	focusItem:function(){
		this.txtDescripcion.focus( true );
	},
	observarReorden:function(node){
		
		if ( Ext.isEmpty(node.attributes.tipo)  ){
			console.log(node);
			
			node.on('move',function(){
				alert("movido");
			},this);
			
			if (node.id=='backlog'){				
				node.attributes.tipo="BACKLOG";
			}else if (node.id=='sprints'){				
				node.attributes.tipo="SPRINTS";				
			}						
		}
	},
    initComponent: function() {
        catHistoria.superclass.initComponent.call(this);
		
		this.txtId.setVisible(false);
		this.txtPadre.setVisible(false);
		this.txtProyecto.setVisible(false);
		
		this.arbolGrid.on('click',function(node, e){			
			if (node.attributes != undefined){
				this.txtId.setValue(node.attributes.id);
				this.recargar();
			}
		},this);
		
		
		var root=this.arbolGrid.getRootNode();
		console.log(root.childNodes);			
		root.on('append',function ( tree, node, node, index ) {
			this.observarReorden(node);			
		},this);				
		
		this.arbolGrid.loader.on('load',function(){
			var root=this.arbolGrid.getRootNode();
			root.expand(true);
		},this);
		
		this.controlador='historias';
		Ext.applyIf(this,comportamiento_formulario);
		this.activarComportamiento();
		
		var form=this.getForm();
		form.on("actioncomplete",function(form, action){
			if (action.type!='load'){
				console.log(action.type);
				this.recargarArbol();
			}
		},this);
		
		this.on('eliminado',this.recargarArbol,this);
		
		this.btnRefresh.on('click',this.recargarArbol,this);
		
		if (this.btnRefresh!=undefined){			
			this.btnRefresh.on('click',this.recargarArbol,this);
		}
		
		this.cmbProyectos.store= new  stoProyectos();
		this.cmbProyectos.store.on('load',function(store , records, options){
			var id_proyecto=this.cmbProyectos.getValue();
			if ( !Ext.isEmpty(id_proyecto) || id_proyecto=="(an empty string)" || id_proyecto==""){				
				this.cmbProyectos.setValue( records[0].id );
				this.cmbProyectos.focus();
				this.recargarArbol();
			}
		},this);
		
		
		var loader=this.arbolGrid.loader;
		loader.on("beforeload", function(treeLoader, node) {
			if (this.baseParams == undefined) this.baseParams={};
			loader.baseParams.proyecto_id = this.cmbProyectos.getValue();			
		}, this);
		
		 
		 
		this.cmbProyectos.on('select',function(combo, record, index){
						
			var root = this.arbolGrid.getRootNode();
			root.setText( record.data.nombre );
									
			this.recargarArbol();
			
			this.arbolGrid.proyectoId = record.data.id;
			
		},this);
		
		this.cmbProyectos.store.load();
		//this.recargarArbol();
		
    },
	recargarArbol:function(){
		var id = this.cmbProyectos.getValue();
		
		//if ( id == this.arbolGrid.proyectoId) 	return;			
		
		var arbol=this.arbolGrid;
		var root=arbol.getRootNode();
		var loader=arbol.loader;
		loader.load(root);
		root.expand(true);
				
		
		root.setText( this.cmbProyectos.getRawValue() );
	},	
	onNuevo:function(){
		var selMod=this.arbolGrid.getSelectionModel();
		var node = selMod.getSelectedNode();
		this.txtProyecto.setValue( this.cmbProyectos.getValue() );
		
		if (node==undefined) {
			this.txtPadre.setValue( 1 );
		}else{
			this.txtPadre.setValue(node.attributes.id);		
		}				
	},
	getForm:function(){
		return this.frmEdicion.getForm();
	}	
});
Ext.reg('catHistoria', catHistoria);