/*
 * File: edicionHistoria.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

edicionHistoriaUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Edicion',
    width: 400,
    padding: 10,
    autoScroll: true,
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Guardar',
                    iconCls: 'btnGuardarIcon_16',
                    itemId: 'btnGuardar',
                    arrowAlign: 'bottom',
                    ref: '../btnGuardar'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    iconCls: 'btnEliminarIcon_16',
                    itemId: 'btnEliminar',
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    iconCls: 'btnNuevoIcon_16',
                    itemId: 'btnNuevo',
                    ref: '../btnNuevo'
                },
                {
                    xtype: 'button',
                    text: 'Recargar',
                    iconCls: 'btnRecargarIcon_16',
                    itemId: 'btnRecargar',
                    ref: '../btnRecargar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'label',
                    text: 'Estado:'
                },
                {
                    xtype: 'tbspacer',
                    width: 10
                },
                {
                    xtype: 'combo'
                },
                {
                    xtype: 'tbspacer',
                    width: 10
                },
                {
                    xtype: 'tbfill'
                }
            ]
        };
        this.items = [
            {
                xtype: 'textfield',
                fieldLabel: 'Id',
                anchor: '100%',
                name: 'id',
                ref: 'txtId'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Nombre',
                anchor: '100%',
                name: 'descripcion',
                ref: 'txtDescripcion'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'sprint',
                anchor: '100%',
                name: 'fk_sprint',
                ref: 'txtSprint'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Importancia',
                name: 'importancia',
                width: 150
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Proyecto',
                anchor: '100%',
                name: 'fk_proyecto',
                ref: 'lblProyecto'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Estimación inicial',
                name: 'estimado',
                width: 150
            },
            {
                xtype: 'displayfield',
                value: '<label style="cursor:pointer !important;">puntos de historia</label>',
                style: 'text-decoration:underline;\ncursor:pointer !important;\ntop:-5px;\nposition:relative;\ntext-align:right;',
                width: 150
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Estado',
                name: 'estado',
                ref: 'txtEstado'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Backlog?',
                anchor: '100%',
                name: 'es_backlog',
                ref: 'txtBacklog'
            },
            {
                xtype: 'htmleditor',
                fieldLabel: 'Notas',
                anchor: '100%',
                height: 400,
                name: 'detalles'
            },
            {
                xtype: 'textarea',
                anchor: '100%',
                fieldLabel: 'Como probarlo',
                name: 'como_probarlo',
                height: 200
            }
        ];
        edicionHistoriaUi.superclass.initComponent.call(this);
    }
});
