/*
 * File: edicionHistoria.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

edicionHistoriaUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Edicion',
    width: 400,
    padding: 10,
    initComponent: function() {
        this.items = [
            {
                xtype: 'textfield',
                fieldLabel: 'Id',
                anchor: '100%',
                name: 'id',
                ref: 'txtId'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Nombre',
                anchor: '100%',
                name: 'descripcion',
                ref: 'txtDescripcion'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'sprint',
                anchor: '100%',
                name: 'fk_sprint',
                ref: 'txtSprint'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Dificultad',
                name: 'dificultad'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Proyecto',
                anchor: '100%',
                name: 'fk_proyecto',
                ref: 'lblProyecto'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Tiempo estimado',
                name: 'estimado'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Estado',
                name: 'estado'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Backlog?',
                anchor: '100%',
                name: 'es_backlog',
                ref: 'txtBacklog'
            },
            {
                xtype: 'htmleditor',
                fieldLabel: 'Detalles',
                anchor: '100%',
                height: 400,
                name: 'detalles'
            }
        ];
        this.tbar = {
            ref: 'tbCrud',
            xtype: 'crud16_toolbar'
        };
        edicionHistoriaUi.superclass.initComponent.call(this);
    }
});
