/*
 * File: grid_catalogo_32.js
 * Date: Thu Sep 13 2012 18:46:42 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

grid_catalogo_32 = Ext.extend(grid_catalogo_32Ui, {
    initComponent: function() {
        grid_catalogo_32.superclass.initComponent.call(this);
    }
});
Ext.reg('grid_catalogo_32', grid_catalogo_32);