/*
 * File: CAMBIAR_Clase.js
 * Date: Sun Sep 16 2012 20:58:08 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

CAMBIAR_Clase = Ext.extend(CAMBIAR_ClaseUi, {    
	initComponent: function() {
        CAMBIAR_Clase.superclass.initComponent.call(this);
		this.controlador='controlador';
		
		this.on("afterrender",function(){
			Ext.applyIf(this,comportamiento_formulario);		
			this.activarComportamiento();			
		},this);
		
    },
	actualizarTitulo:function(	action ){		
		if (action=="guardado" || action=="edicion")
			this.setTitle(this.txtNombre.getValue() );
	}
});
Ext.reg('CAMBIAR_xtype', CAMBIAR_Clase);