/*
 * File: CAMBIAR_Clase.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

CAMBIAR_ClaseUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Edicion',
    width: 400,
    height: 250,
    padding: 10,
    initComponent: function() {
        this.items = [
            {
                xtype: 'textfield',
                fieldLabel: 'Id',
                anchor: '100%',
                name: 'id',
                ref: 'txtId'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Nombre',
                anchor: '100%',
                name: 'nombre',
                ref: 'txtNomPub'
            }
        ];
        this.tbar = {
            ref: 'tbCrud',
            xtype: 'crud16_toolbar'
        };
        CAMBIAR_ClaseUi.superclass.initComponent.call(this);
    }
});
