/*
 * File: gridPendientes.js
 * Date: Sun Sep 09 2012 07:34:20 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

gridPendientes = Ext.extend(gridPendientesUi, {
    initComponent: function() {
        gridPendientes.superclass.initComponent.call(this);
		this.store=new stoPendientes({
			url: '/Ctrl_Pendientes/listar',
			writer:new Ext.data.JsonWriter({
				encode: true,
				writeAllFields: true // write all fields, not just those that changed
			})
		});
		this.store.on('beforeload',function(store, options){			
			options.params={base:this.initialConfig.id};			
		},this);
		
		this.setTitle(this.initialConfig.text);
	//----------------------------------
	//  para que este grid se comporte como un grid del catalogo crud, ejecutamos la siguiente linea
	
		Ext.apply(this,comportamiento_grid,{
			xtype_del_form:"frmPendientes"
		});	
		
	//  y asi se activa el comportamiento
		this.activarComportamiento();
	//----------------------------------				
    }
});
Ext.reg('gridPendientes', gridPendientes);