/*
 * File: gridPendientes.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridPendientesUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Listado',
    width: 449,
    height: 254,
    autoExpandColumn: 'colNombre',
    initComponent: function() {
        this.tbar = {
            xtype: 'grid_catalogo_32'
        };
        this.bbar = {
            xtype: 'paging',
            displayInfo: true
        };
        this.columns = [
            {
                xtype: 'gridcolumn',
                header: 'Nombre',
                dataIndex: 'nombre',
                sortable: true,
                width: 100,
                id: 'colNombre'
            },
            {
                xtype: 'gridcolumn',
                header: 'Prioridad',
                dataIndex: 'prioridad',
                sortable: true,
                width: 100
            }
        ];
        gridPendientesUi.superclass.initComponent.call(this);
    }
});
