/*
 * File: stoPendientes.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

stoPendientes = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        stoPendientes.superclass.constructor.call(this, Ext.apply({
            root: 'datos',
            messageProperty: 'msg',
            api: {
                read: '/Ctrl_Pendientes/listar',
                create: '/Ctrl_Pendientes/crear',
                update: '/Ctrl_Pendientes/guardar',
                destroy: '/Ctrl_Pendientes/eliminar'
            },
            fields: [
                {
                    name: 'uuid'
                },
                {
                    name: 'id'
                },
                {
                    name: 'nombre'
                },
                {
                    name: 'prioridad'
                }
            ]
        }, cfg));
    }
});
Ext.reg('stoPendientes', stoPendientes);