/*
 * File: frmModelo.js
 * Date: Sun Aug 12 2012 20:35:38 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

frmModelo = Ext.extend(frmModeloUi, {
    initComponent: function() {
        frmModelo.superclass.initComponent.call(this);
    }
});
Ext.reg('frmModelo', frmModelo);