/*
 * File: frmModelo.ui.js
 * Date: Tue Aug 14 2012 20:25:11 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

frmModeloUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Edicion',
    width: 400,
    height: 250,
    padding: 10,
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Guardar',
                    iconCls: 'btnGuardarIcon',
                    itemId: 'btnGuardar',
                    scale: 'medium',
                    arrowAlign: 'bottom',
                    iconAlign: 'top',
                    ref: '../btnGuardar'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    iconCls: 'btnEliminarIcon',
                    itemId: 'btnEliminar',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    iconCls: 'btnNuevoIcon',
                    itemId: 'btnNuevo',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnNuevo'
                },
                {
                    xtype: 'button',
                    text: 'Recargar',
                    iconCls: 'btnRecargarIcon',
                    itemId: 'btnRecargar',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnRecargar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    text: 'Switch',
                    iconCls: 'btnSwitchIcon',
                    itemId: 'btnSwitch',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnSwitch'
                }
            ]
        };
        this.items = [
            {
                xtype: 'textarea',
                anchor: '100%',
                fieldLabel: 'UUID',
                name: 'uuid'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'ID',
                anchor: '100%',
                name: 'id'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'nombre',
                anchor: '100%',
                name: 'nombre'
            }
        ];
        frmModeloUi.superclass.initComponent.call(this);
    }
});
