/*
 * File: MyForm.ui.js
 * Date: Fri Aug 17 2012 22:10:48 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyFormUi = Ext.extend(Ext.form.FormPanel, {
    title: 'My Form',
    width: 649,
    height: 547,
    padding: 10,
    layout: 'auto',
    initComponent: function() {
        this.items = [
            {
                xtype: 'textfield',
                height: 50,
                width: 350
            },
            {
                xtype: 'container',
                defaults: {
                    width: 80,
                    height: 80,
                    style: 'margin-left:10px; margin-bottom:10px;'
                },
                layout: 'table',
                itemId: 'contTecladoNumerico',
                width: 315,
                style: 'margin-top:10px;float:left;',
                ref: 'contTecladoNumerico',
                layoutConfig: {
                    columns: 3
                },
                items: [
                    {
                        xtype: 'button',
                        text: 1
                    },
                    {
                        xtype: 'button',
                        text: 2
                    },
                    {
                        xtype: 'button',
                        text: 3
                    },
                    {
                        xtype: 'button',
                        text: 4
                    },
                    {
                        xtype: 'button',
                        text: 5
                    },
                    {
                        xtype: 'button',
                        text: 6
                    },
                    {
                        xtype: 'button',
                        text: 7
                    },
                    {
                        xtype: 'button',
                        text: 8
                    },
                    {
                        xtype: 'button',
                        text: 9
                    },
                    {
                        xtype: 'button',
                        text: 'O',
                        colspan: 2,
                        width: 170
                    },
                    {
                        xtype: 'button',
                        text: '.asd',
                        style: 'font-size:50px !important;font-weight:bold !important;',
                        scale: 'large'
                    }
                ]
            },
            {
                xtype: 'container',
                width: 200,
                style: 'float:left;margin-top:10px;',
                defaults: {
                    width: 40,
                    height: 40,
                    style: 'margin-left:10px; margin-bottom:10px;'
                },
                layout: 'table',
                layoutConfig: {
                    columns: 3
                },
                items: [
                    {
                        xtype: 'button',
                        text: '+'
                    },
                    {
                        xtype: 'button',
                        text: '-'
                    },
                    {
                        xtype: 'button',
                        text: 'MyButton'
                    },
                    {
                        xtype: 'button',
                        text: 'MyButton'
                    },
                    {
                        xtype: 'button',
                        text: 'MyButton'
                    },
                    {
                        xtype: 'button',
                        text: 'MyButton'
                    },
                    {
                        xtype: 'button',
                        text: 'MyButton'
                    },
                    {
                        xtype: 'button',
                        text: 'MyButton'
                    },
                    {
                        xtype: 'button',
                        text: 'MyButton'
                    }
                ]
            }
        ];
        MyFormUi.superclass.initComponent.call(this);
    }
});
