/*
 * File: Scrum.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

ScrumUi = Ext.extend(Ext.Panel, {
    title: 'Historias de usuario y tareas',
    height: 250,
    layout: 'border',
    bodyStyle: '',
    initComponent: function() {
        this.items = [
            {
                xtype: 'treepanel',
                region: 'west',
                width: 320,
                border: false,
                split: true,
                collapseMode: 'mini',
                rootVisible: false,
                hlDrop: false,
                ref: 'arbolGrid',
                root: {
                    text: 'Proyecto',
                    expanded: true,
                    id: 'proyecto',
                    children: [
                        {
                            text: 'Backlog',
                            draggable: true,
                            leaf: true,
                            id: 'backlog'
                        },
                        {
                            text: 'Sprints',
                            draggable: true,
                            id: 'sprints'
                        }
                    ]
                },
                loader: {
                    url: '/sprints/getSprints'
                },
                bbar: {
                    xtype: 'toolbar',
                    style: 'border-width:1px 1px 0 0;',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            iconCls: 'x-tbar-loading',
                            ref: '../../btnRefresh'
                        }
                    ]
                },
                tbar: {
                    xtype: 'toolbar',
                    items: [
                        {
                            xtype: 'spacer',
                            width: 5
                        },
                        {
                            xtype: 'displayfield',
                            value: 'Proyecto',
                            style: 'text-decoration:underline;font-weight:bold;cursor:pointer;',
                            ref: '../../lblProyecto'
                        },
                        {
                            xtype: 'spacer',
                            width: 5
                        },
                        {
                            xtype: 'combo',
                            valueField: 'id',
                            displayField: 'nombre',
                            minChars: 0,
                            triggerAction: 'all',
                            itemId: 'cmbProyectos',
                            emptyText: 'cargando proyectos...',
                            ref: '../../cmbProyectos'
                        }
                    ]
                }
            },
            {
                xtype: 'tabpanel',
                activeTab: 0,
                region: 'center',
                itemId: 'tabPanel',
                ref: 'tabPanel',
                items: [
                    {
                        xtype: 'panel',
                        title: 'BackLog'
                    }
                ]
            }
        ];
        ScrumUi.superclass.initComponent.call(this);
    }
});
