/*
 * File: gridHistoriadeUsuario.ui.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridHistoriadeUsuarioUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Historias de usuario',
    autoExpandColumn: 'colDescripcion',
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Editar',
                    iconCls: 'btnEditarIcon_16',
                    itemId: 'btnEditar',
                    arrowAlign: 'bottom',
                    ref: '../btnEditar'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    iconCls: 'btnEliminarIcon_16',
                    itemId: 'btnEliminar',
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    iconCls: 'btnNuevoIcon_16',
                    itemId: 'btnNuevo',
                    ref: '../btnNuevo'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    iconCls: 'btnDown_16',
                    itemId: 'btnDown',
                    ref: '../btnDown'
                },
                {
                    xtype: 'button',
                    iconCls: 'btnUp_16',
                    itemId: 'btnUp',
                    ref: '../btnUp'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'displayfield',
                    value: 'Proyecto'
                },
                {
                    xtype: 'combo',
                    displayField: 'nombre',
                    valueField: 'id',
                    minChars: 0,
                    triggerAction: 'all',
                    ref: '../cmbProyectos'
                },
                {
                    xtype: 'displayfield',
                    value: 'Ubicacion:'
                },
                {
                    xtype: 'combo',
                    emptyText: 'seleccione ubicacion',
                    displayField: 'nombre',
                    valueField: 'id',
                    minChars: 0,
                    triggerAction: 'all',
                    ref: '../cmbUbicaciones'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'tbspacer',
                    width: 10
                },
                {
                    xtype: 'displayfield',
                    value: 'Estado',
                    style: 'font-weighr:bold;cursor:pointer; text-decoration:underline;'
                },
                {
                    xtype: 'tbspacer',
                    width: 10
                },
                {
                    xtype: 'combo',
                    valueField: 'id',
                    displayField: 'nombre',
                    minChars: 0,
                    triggerAction: 'all',
                    tpl: [
                        '<tpl for="."><div class="x-combo-list-item" style="clear:both"><div class="scrum_estado_id_{id}" style="float:left;"></div><div style="float:left; margin-left:10px;">{nombre}</div></div>',
                        '</tpl>'
                    ],
                    ref: '../cmbEstado'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'trigger',
                    triggerClass: 'x-form-search-trigger',
                    ref: '../txtSearch'
                }
            ]
        };
        this.bbar = {
            xtype: 'paging',
            displayInfo: true
        };
        this.columns = [
            {
                xtype: 'templatecolumn',
                header: 'E',
                sortable: true,
                width: 25,
                dataIndex: 'fk_estado',
                tpl: '<div class="scrum_estado_id_{fk_estado}" title="estado"></div>',
                align: 'center'
            },
            {
                xtype: 'gridcolumn',
                header: 'descripcion',
                dataIndex: 'descripcion',
                sortable: true,
                width: 100,
                id: 'colDescripcion'
            },
            {
                xtype: 'gridcolumn',
                header: 'Estimado',
                sortable: true,
                width: 100,
                dataIndex: 'estimado',
                hidden: true
            },
            {
                xtype: 'gridcolumn',
                header: 'Duracion',
                sortable: true,
                width: 100,
                dataIndex: 'duracion',
                hidden: true
            }
        ];
        gridHistoriadeUsuarioUi.superclass.initComponent.call(this);
    }
});
