/*
 * File: HistoriasYTareas.ui.js
 * Date: Fri Oct 26 2012 21:35:42 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

HistoriasYTareasUi = Ext.extend(Ext.Panel, {
    title: 'My Panel',
    height: 250,
    layout: 'fit',
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Editar',
                    iconCls: 'btnEditarIcon_16',
                    itemId: 'btnEditar',
                    arrowAlign: 'bottom',
                    ref: '../btnEditar'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    iconCls: 'btnEliminarIcon_16',
                    itemId: 'btnEliminar',
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    iconCls: 'btnNuevoIcon_16',
                    itemId: 'btnNuevo',
                    ref: '../btnNuevo'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'button',
                    iconCls: 'btnDown_16',
                    itemId: 'btnDown',
                    ref: '../btnDown'
                },
                {
                    xtype: 'button',
                    iconCls: 'btnUp_16',
                    itemId: 'btnUp',
                    ref: '../btnUp'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'displayfield',
                    value: 'Proyecto'
                },
                {
                    xtype: 'combo',
                    displayField: 'nombre',
                    valueField: 'id',
                    minChars: 0,
                    triggerAction: 'all',
                    ref: '../cmbProyectos'
                },
                {
                    xtype: 'displayfield',
                    value: 'Ubicacion:'
                },
                {
                    xtype: 'combo',
                    emptyText: 'seleccione ubicacion',
                    displayField: 'nombre',
                    valueField: 'id',
                    minChars: 0,
                    triggerAction: 'all',
                    ref: '../cmbUbicaciones'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'tbspacer',
                    width: 10
                },
                {
                    xtype: 'displayfield',
                    value: 'Estado',
                    style: 'font-weighr:bold;cursor:pointer; text-decoration:underline;'
                },
                {
                    xtype: 'tbspacer',
                    width: 10
                },
                {
                    xtype: 'combo',
                    valueField: 'id',
                    displayField: 'nombre',
                    minChars: 0,
                    triggerAction: 'all',
                    tpl: [
                        '<tpl for="."><div class="x-combo-list-item" style="clear:both"><div class="scrum_estado_id_{id}" style="float:left;"></div><div style="float:left; margin-left:10px;">{nombre}</div></div>',
                        '</tpl>'
                    ],
                    ref: '../cmbEstado'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'trigger',
                    triggerClass: 'x-form-search-trigger',
                    ref: '../txtSearch'
                }
            ]
        };
        this.items = [
            {
                ref: 'arbolScrum',
                xtype: 'tree_historias_y_tareas'
            }
        ];
        HistoriasYTareasUi.superclass.initComponent.call(this);
    }
});
