/*
 * File: HistoriasYTareas.js
 * Date: Fri Oct 26 2012 19:12:07 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

HistoriasYTareas = Ext.extend(HistoriasYTareasUi, {
	xtype_del_form:"edicion_historias_y_tareas",	
	//plugins:[CatGridPlugin],    	
	/*editParams:function(){
		imagenes\Human-O2\128x128\apps
	},*/
	
	
    initComponent: function() {
        HistoriasYTareas.superclass.initComponent.call(this);
		
		Ext.applyIf(this, CatGridFunctions);
		//----------------------------------
		//this.store=new stoHistoriasYTareas();
		//----------------------------------
		//this.configurarGrid();				
		//----------------------------------		
		this.configArbolScrum();
		
		this.configComboMover();
		
		this.configBotonesMover();		
		
		this.configComboEstados();
				
		this.configurarComboProyectos();		
		
		//this.configComboUbicacion();		
		this.cmbUbicaciones.on("select",function(){
			this.arbolScrum.actualizar();
		},this);
		
		this.enableBubble("mostrarTab");	
		
		this.cofigCrudToolbar(this);			
		
		this.btnNuevaTarea.on('click',function(){
			var sel = this.getSelected();
			console.log(sel);
			if (sel==undefined){
				return false;
			}
			
			if (sel.data.tipo!='historia') return false;
			
			this.nuevaTarea(sel.id);
		},this);
    },
	getGrid:function(){
		return this.arbolScrum;
	},
	configArbolScrum:function(){
		this.arbolScrum.cmbProyectos   = this.cmbProyectos;
		this.arbolScrum.cmbUbicaciones = this.cmbUbicaciones;
		this.arbolScrum.configArbol();
		
		this.arbolScrum.on('editarHistoria',function(idHistoria){			
			this.editarHistoria(idHistoria);
		},this);
		
		this.arbolScrum.on('editarTarea',function(idTarea){			
			this.editarTarea(idTarea);
		},this);
		
		this.arbolScrum.on('click',function( node, e ){			
			console.log( node );
			this.mostrarOcultarBotones();
			var selMod= this.arbolScrum.getSelectionModel();
			//console.log();
			//selMod.selNode= node;
		},this);
		
		var selMod=this.arbolScrum.getSelectionModel();
		selMod.getCount=function(){
			if (selMod.selNode==undefined){
				return 0;
			}else{
				return 1;
			}								
		}
		selMod.getSelected=function(){
			
		}
	},	
	getSelected: function(){
		var selMod=this.arbolScrum.getSelectionModel();
		
		if (selMod.selNode!=undefined){							
			return {					
				id:selMod.selNode.id,
				data:selMod.selNode.attributes
			};	
		}else{
			return selMod.selNode;
		}
	},
	editParams:function(params){
		var ubicacion={};
		var idUbicacion=this.cmbUbicaciones.getValue();		
		if (idUbicacion != "backlog" && idUbicacion != "sprints"){
			ubicacion.sprintId=idUbicacion;
		}
		params.masConfig=ubicacion;
		return params;
	},	
	configurarGrid:function(){
		this.on('rowcontextmenu',function( grid, rowIndex, e ){		
			var xy = e.getXY();						
			var record=this.getStore().getAt( rowIndex );			
			var menu = this.getContextMenu();
			menu.showAt(xy);
			menu.idUbicacion=this.cmbUbicaciones.getValue();
			menu.selected=record.data;
			e.stopEvent();
			return false;
		},this);
		
		this.store.on('beforeload',function(store, options){			
		//PENDIENTE: Explicar este bloque de codigo
			if (this.initialConfig.tipo == undefined) 
				this.initialConfig.tipo='backlog';
			options.params.tipo=this.initialConfig.tipo;			
			options.params.idUbicacion=this.cmbUbicaciones.getValue();
			if (this.initialConfig.tipo=='sprint'){			
				options.params.sprintId=this.initialConfig.idSprint;				
			}
			
		},this);
		
		this.store.on('load',function(store, records, options){
			if (options.params!=undefined)
			if (options.params.idSeleccionado != undefined && options.params.idSeleccionado!=0){
				var record= store.getById(options.params.idSeleccionado);				
				var index=-1;
				if (record!=undefined)
					index= store.indexOf( record );
				
				if (index>-1){
					this.getSelectionModel().selectRow(index);
				}				
			}							
		},this);
	},
	
	
	configComboMover:function(){
		this.cmbUbicaciones.store=new stoProyectos({
			idProperty:'id',
			url: '/historias/listarUbicaciones'
		});		
		
		this.cmbUbicaciones.on("select",function(){
	//		this.bottomToolbar.doRefresh();
		},this);
	},
	configComboEstados:function(){
	
		this.cmbEstado.store=new stoEstadoHistoria();
		this.cmbEstado.on('select',function( combo, record, index){
			// Filtrar la busqueda por el estado seleccionado.
			//this.bottomToolbar.doRefresh();
			this.arbolScrum.actualizar();
		},this);
    },
	configBotonesMover:function(){
	
		this.btnUp.on("click",this.moverArriba,this);
		this.btnDown.on("click",this.moverAbajo,this);
		
	},
	//Muestra sprints y Backlog , filtra la ubicacion actual		
	moverArriba:function(){
		this.moverHistoria('up');
	},
	moverAbajo:function(){
		this.moverHistoria('down');
	},
	moverHistoria:function(direccion){
		var idHistoria=0;
		
		var grid=this;
		var sel=grid.getSelected();
		if (sel!=undefined) 
			idHistoria=sel.id;
			
		if (idHistoria==0) return false;
		
		Ext.Ajax.request({
		   url: '/historias/mover_historia',
		   params: {
				idHistoria:idHistoria,
				direccion:direccion
		   },
		   scope:this,
		   success: function(response, opts){
			  var result = Ext.decode(response.responseText);			  
			  if (result.success===true){												
				this.bottomToolbar.doRefresh();
			  }else{				
					alert(result.msg); 
			  }			  
		   },
		   failure: function(response, opts) {
			  //console.log('server-side failure with status code ' + response.status);
		   }
		});
	},
	getContextMenu:function(){
		if (this.ctxMenu == undefined)
		this.ctxMenu = new ctxHistoria();
		this.ctxMenu.on('reubicarHistoria',this.preguntarReubicarHistoria, this);
		
		
		this.ctxMenu.cmbMover.store.removeAll();
		this.ctxMenu.cmbMover.reset();
		this.ctxMenu.cmbMover.store.load();
		
		return this.ctxMenu;
	},
	preguntarReubicarHistoria:function(historia, destino){
		//console.log("historia"); console.log(historia);
		//console.log("destino"); console.log(destino);
		Ext.Msg.show({
		   title:'Reubicar?',
		   msg: 'Desea reubicar la historia?',
		   buttons: Ext.Msg.YESNO,
		   scope:this,
		   fn: function(btn){
				if (btn=="yes"){
					this.reubicarHistoria(historia, destino);
				}
		   },		   
		   icon: Ext.MessageBox.QUESTION
		});
		
	},
	reubicarHistoria:function(historia, destino){ //entre sprints y la pila de producto.				
				
		if (historia==undefined || destino==undefined) return;
		var params={
			idHistoria:historia.id,
			idDestino:destino.id
		} ;
		Ext.Ajax.request({
		   url: '/historias/mover',
		   params: params,
		   scope:this,
		   success: function(response, opts){
			  var result = Ext.decode(response.responseText);
			  if (result.success===true){
				this.bottomToolbar.doRefresh();
				if (result.msg)
					topMsg.setAlert("Historias", result.msg); 
			  }else{				
					alert(result.msg); 
			  }			  
		   },
		   failure: function(response, opts) {
			  //console.log('server-side failure with status code ' + response.status);
		   }
		});
	},
	configurarComboProyectos:function(){
		this.cmbProyectos.store= new stoProyecto();		
		
		this.cmbProyectos.initPlugin(cmbScrumProyectoPlugin);		
		this.cmbProyectos.on('proyectoSeleccionado',function(proyectoId){			
			this.seleccionarProyecto( proyectoId );
		},this);
		
		
		this.cmbProyectos.on('select',function(){
			this.seleccionarProyecto();
		},this);
		
		this.cmbProyectos.store.load();		
	},
	seleccionarProyecto:function(){
	
		var idProyecto=this.cmbProyectos.getValue();
		
		Ext.Ajax.request({							//Notifica al servidor del proyecto seleccionado 
			url: '/scrum/seleccionarProyecto',
			params:{idProyecto:idProyecto},
			scope:this,
			success: function( response, options){
			
				var resp=Ext.decode(response.responseText);				
				if (resp.success==true){
					topMsg.setAlert(this.controlador,resp.msg);
					Modulos.Scum.idProyecto = this.cmbProyectos.getValue();
					this.cmbProyectos.setValue(Modulos.Scum.idProyecto);					
					this.cmbUbicaciones.store.removeAll();
					this.cmbUbicaciones.reset();
					this.cmbUbicaciones.store.load();
			//		this.store.loadData({datos:{}});
					this.cmbUbicaciones.setValue('backlog');
				//	this.bottomToolbar.doRefresh();
					this.arbolScrum.actualizar();
				}else{
					this.cmbProyectos.setValue(Modulos.Scum.idProyecto);					
					alert(resp.msg);
				}
			
			},
		   failure: function(){
				alert("FALLA: seleccionarProyecto");
		   }
		});
		
		
		
	},
	editarHistoria:function(id){	//TODO: considerar todos los modelos de seleccion del extjs				
		var params={
			xtype:	this.xtype_del_form,			
			idReg:  id
		};
		
		if ( !Ext.isEmpty(this.iconCls) ){
			params.iconCls=this.iconCls;
		}		
		
		this.fireEvent('mostrarTab',params);
	},
	editarTarea:function(id){	//TODO: considerar todos los modelos de seleccion del extjs				
		var params={
			xtype:	'edicion_tareas',			
			idReg:  id
		};
		
		if ( !Ext.isEmpty(this.iconCls) ){
			params.iconCls=this.iconCls;
		}		
		
		this.fireEvent('mostrarTab',params);
	},
	nuevaTarea:function(fk_historia){
		var params={
			xtype:	'edicion_tareas',			
			idReg:  0,
			fk_historia:fk_historia
		};		
		
		this.fireEvent('mostrarTab',params);
	}
	
	
});
Ext.reg('historias_y_tareas', HistoriasYTareas);