/*
 * File: stoHistoriasDUsuario.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

stoHistoriasYTareas = Ext.extend(Ext.data.GroupingStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        stoHistoriasYTareas.superclass.constructor.call(this, Ext.apply({			
			api:{
				read: '/Historias/paginarHistorias',
				create: '/Historias/crear',
				update: '/Historias/guardar',
				destroy: '/Historias/eliminar'
			},
			reader : new Ext.data.JsonReader({
				root: 'datos',
				idProperty: 'id',
				fields: [
					{
						name: 'id'
					},
					{
						name: 'idHistoria'
					},
					{
						name: 'historia'
					},
					{
						name: 'idTarea'
					},
					{
						name: 'tarea'
					},
					{
						name: 'estado'
					}
				]
			}),
			writer:new Ext.data.JsonWriter({
				encode: true,
				writeAllFields: true // write all fields, not just those that changed
			}),            
			groupField:'historia'			
        }, cfg));
    }
});
Ext.reg('stoHistoriasYTareas', stoHistoriasYTareas);