/*
 * File: stoHistoriasDUsuario.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

stoHistoriasYTareas = Ext.extend(Ext.data.GroupingStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        stoHistoriasYTareas.superclass.constructor.call(this, Ext.apply({			
			api:{
				read: '/Historias/listar',
				create: '/Historias/crear',
				update: '/Historias/guardar',
				destroy: '/Historias/eliminar'
			},
			reader : new Ext.data.JsonReader({root: 'datos',
				idProperty: 'id',
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'descripcion'
                },
                {
                    name: 'estimado'
                },
                {
                    name: 'default'
                },
                {
                    name: 'fk_estado'
                },
                {
                    name: 'desc_estado'
                },
                {
                    name: 'duracion'
                }
            ]}),
			writer:new Ext.data.JsonWriter({
				encode: true,
				writeAllFields: true // write all fields, not just those that changed
			}),
            storeId: 'stoHistoriasYTareas',
            root: 'datos',
			groupField:'descripcion',
			idProperty:'id'
			
    
			
        }, cfg));
    }
});
Ext.reg('stoHistoriasYTareas', stoHistoriasYTareas);