/*
 * File: tabPanel.js
 * Date: Sun Aug 12 2012 20:32:25 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

tabPanel = Ext.extend(tabPanelUi, {
    initComponent: function() {
        tabPanel.superclass.initComponent.call(this);		
		Ext.apply(this, comportamiento_tab_manager);
		
		this.activarComportamiento();
		
    }
});
Ext.reg('tabPanel', tabPanel);