/*
 * File: edicion_historias_y_tareas.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

edicion_historias_y_tareas = Ext.extend(edicion_historias_y_tareasUi, {
    initComponent: function() {        
		edicion_historias_y_tareas.superclass.initComponent.call(this);
		
		this.txtId.setVisible(false);
		this.txtSprint.setVisible(false);
		this.txtBacklog.setVisible(false);
		this.txtEstado.setVisible(false);
		this.txtNombreEstado.setVisible(false);
		this.lblProyecto.setVisible(false);
		this.controlador='historias';
		
		
			Ext.applyIf(this,comportamiento_formulario);		
			this.activarComportamiento();			
		
		this.enableBubble('mostrarTab');
		this.btnVerTareas.on('click',function(){
			var params={
				xtype:	'grid_tareas',				
				idHistoria:  this.txtId.getValue()
			};			
			
			this.fireEvent('mostrarTab',params);
		},this);
				
		
		this.cmbEstado.store=new stoEstadoHistoria();
		this.cmbEstado.on('select',function( combo, record, index){
			this.txtEstado.setValue(record.id);
		},this);
		
		this.cmbEstado.on('cargado',function( combo, record, index){		
			//No nos confiamos en si el combo ya tiene los datos, por estandar, se carga tambien el valor a mostrar, en este caso, nombreEstado											
			var estado={
				id:this.txtEstado.getValue(),
				nombre:this.txtNombreEstado.getValue()
			};
			this.cmbEstado.store.loadData({datos:estado});
			this.cmbEstado.setValue(estado.id);			
		},this);		
		this.cmbEstado.store.load();
				
		this.on('guardado',function(){			
			this.cargarCombos();
		},this);
		
		this.on('cargado',function(){	
			var id=this.txtId.getValue();
			if (id==0){
				var sprintId=this.initialConfig.masConfig.sprintId;
				if ( sprintId!=undefined){
					this.txtSprint.setValue(sprintId);
					this.txtBacklog.setValue(0);
				}else{
					this.txtSprint.setValue(0);				
					this.txtBacklog.setValue(1);				
				}
				
			}else{
				var idUbicacion=this.txtSprint.getValue();
				
				if (this.initialConfig.masConfig == undefined)
					this.initialConfig.masConfig={};
					
				if ( !isNaN(idUbicacion) )
					this.initialConfig.masConfig.sprintId = idUbicacion;
			}
			this.cargarCombos();
		},this);				
		
    },
	cargarCombos:function(){
		var estado={
			id:this.txtEstado.getValue(),
			nombre:this.txtNombreEstado.getValue()
		};
		this.cmbEstado.store.loadData({datos:estado});
		this.cmbEstado.setValue(estado.id);
	},	
	
	actualizarTitulo:function(	action ){
		if (action=="guardado" || action=="edicion")
			this.setTitle(this.txtDescripcion.getValue() );
	}
});
Ext.reg('edicion_historias_y_tareas', edicion_historias_y_tareas);