/*
 * File: gridModelo.ui.js
 * Date: Fri Sep 07 2012 22:18:39 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

gridModeloUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Listado',
    store: 'stoModelo',
    width: 449,
    height: 254,
    autoExpandColumn: 'colNombre',
    initComponent: function() {
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    iconCls: 'btnNuevoIcon',
                    itemId: 'btnNuevo',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnNuevo'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    iconCls: 'btnEliminarIcon',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'button',
                    text: 'Editar',
                    iconCls: 'btnEditarIcon',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnEditar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'textfield',
                    itemId: 'txtSearch',
                    ref: '../txtSearch'
                },
                {
                    xtype: 'button',
                    text: 'Switch',
                    iconCls: 'btnSwitchIcon',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnSwitch'
                }
            ]
        };
        this.bbar = {
            xtype: 'paging',
            store: 'stoModelo',
            displayInfo: true
        };
        this.columns = [
            {
                xtype: 'gridcolumn',
                header: 'Nombre',
                dataIndex: 'nombre',
                sortable: true,
                width: 100,
                id: 'colNombre'
            },
            {
                xtype: 'gridcolumn',
                header: 'Prioridad',
                dataIndex: 'prioridad',
                sortable: true,
                width: 100
            }
        ];
        gridModeloUi.superclass.initComponent.call(this);
    }
});
