/*
 * File: frmProyecto.js
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

frmProyecto = Ext.extend(frmProyectoUi, {
    initComponent: function() {
        frmProyecto.superclass.initComponent.call(this);
		
		this.txtId.setVisible(false);
		
		this.controlador='proyectos';
		
		this.on("afterrender",function(){
			Ext.applyIf(this,comportamiento_formulario);		
			this.activarComportamiento();			
		},this);
		
    },
	actualizarTitulo:function(	action ){		
		if (action=="guardado" || action=="edicion")
			this.setTitle(this.txtNombre.getValue() );
	}
});
Ext.reg('frmProyecto', frmProyecto);