/*
 * File: frmPendientes.ui.js
 * Date: Sun Sep 09 2012 08:48:34 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

frmPendientesUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Edicion',
    padding: 10,
    url: '/ctrl_pendientes/obtener',
    autoScroll: true,
    method: 'POST',
    initComponent: function() {
        this.initialConfig = Ext.apply({
            url: '/ctrl_pendientes/obtener',
            method: 'POST'
        }, this.initialConfig);
        this.items = [
            {
                xtype: 'container',
                layout: 'form'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'ID',
                name: 'id',
                readOnly: true,
                ref: 'txtId'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'nombre',
                name: 'nombre',
                width: 300
            },
            {
                xtype: 'numberfield',
                fieldLabel: 'Prioridad',
                value: 0,
                style: 'text-align:right;',
                width: 50,
                name: 'prioridad'
            },
            {
                xtype: 'htmleditor',
                fieldLabel: 'Descripción',
                name: 'descripcion',
                height: 197,
                width: 600
            },
            {
                xtype: 'grid',
                store: 'stoTareas',
                height: 210,
                width: 500,
                autoExpandColumn: 'colDesc',
                fieldLabel: 'Tareas',
                style: 'margin-top:20px;',
                columns: [
                    {
                        xtype: 'numbercolumn',
                        dataIndex: 'string',
                        header: 'Prioridad',
                        sortable: true,
                        width: 100,
                        align: 'right'
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'number',
                        header: 'Nombre',
                        sortable: true,
                        width: 100,
                        align: 'right',
                        id: 'colNombre'
                    },
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'date',
                        header: 'Descripcion',
                        sortable: true,
                        width: 100,
                        id: 'colDesc'
                    }
                ],
                bbar: {
                    xtype: 'paging',
                    displayInfo: true
                }
            }
        ];
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Guardar',
                    iconCls: 'btnGuardarIcon',
                    itemId: 'btnGuardar',
                    scale: 'medium',
                    arrowAlign: 'bottom',
                    iconAlign: 'top',
                    ref: '../btnGuardar'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    iconCls: 'btnEliminarIcon',
                    itemId: 'btnEliminar',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    iconCls: 'btnNuevoIcon',
                    itemId: 'btnNuevo',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnNuevo'
                },
                {
                    xtype: 'button',
                    text: 'Recargar',
                    iconCls: 'btnRecargarIcon',
                    itemId: 'btnRecargar',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnRecargar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    text: 'Switch',
                    iconCls: 'btnSwitchIcon',
                    itemId: 'btnSwitch',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnSwitch'
                }
            ]
        };
        frmPendientesUi.superclass.initComponent.call(this);
    }
});
