/*
 * File: frmPendientes.js
 * Date: Sun Sep 09 2012 08:48:34 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

frmPendientes = Ext.extend(frmPendientesUi, {
	
	
    initComponent: function() {
        frmPendientes.superclass.initComponent.call(this);
		this.txtId.setVisible(false);
		
		
			Ext.applyIf(this,comportamiento_formulario);
			this.controlador='ctrl_pendientes';
			this.activarComportamiento();		
		
		
		
    },
	actualizarTitulo:function(	action ){			
		if (action=="guardado" || action=="edicion")
			this.setTitle( this.txtNombre.getValue() );
	}
});
Ext.reg('frmPendientes', frmPendientes);