/*
 * File: frmPendientes.ui.js
 * Date: Thu Sep 13 2012 22:59:52 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

frmPendientesUi = Ext.extend(Ext.form.FormPanel, {
    title: 'Edicion',
    padding: 10,
    url: '/ctrl_pendientes/obtener',
    autoScroll: true,
    method: 'POST',
    labelAlign: 'top',
    initComponent: function() {
        this.initialConfig = Ext.apply({
            url: '/ctrl_pendientes/obtener',
            method: 'POST'
        }, this.initialConfig);
        this.items = [
            {
                xtype: 'container',
                layout: 'form'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'ID',
                name: 'id',
                readOnly: true,
                value: 0,
                ref: 'txtId'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Historia / Actividad',
                anchor: '80%',
                name: 'nombre',
                width: 300,
                ref: 'txtNombre'
            },
            {
                xtype: 'numberfield',
                fieldLabel: 'Prioridad',
                value: 0,
                style: 'text-align:right;',
                width: 50,
                name: 'prioridad'
            },
            {
                xtype: 'fieldset',
                title: 'Descripcion',
                layout: 'fit',
                collapsible: true,
                style: '',
                collapsed: true,
                animCollapse: true,
                items: [
                    {
                        xtype: 'htmleditor',
                        name: 'descripcion',
                        height: 370,
                        width: 600
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Tareas',
                collapsible: true,
                animCollapse: true,
                height: 400,
                layout: 'fit',
                items: [
                    {
                        xtype: 'tabpanel',
                        activeTab: 0,
                        ref: '../tabTareas',
                        items: [
                            {
                                title: 'Lista de Tareas',
                                ref: '../../gridTareas',
                                xtype: 'gridTareas'
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Label',
                anchor: '100%',
                name: 'grupo',
                ref: 'txtGrupo'
            }
        ];
        this.tbar = {
            xtype: 'toolbar',
            items: [
                {
                    xtype: 'button',
                    text: 'Guardar',
                    iconCls: 'btnGuardarIcon',
                    itemId: 'btnGuardar',
                    scale: 'medium',
                    arrowAlign: 'bottom',
                    iconAlign: 'top',
                    ref: '../btnGuardar'
                },
                {
                    xtype: 'button',
                    text: 'Eliminar',
                    iconCls: 'btnEliminarIcon',
                    itemId: 'btnEliminar',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnEliminar'
                },
                {
                    xtype: 'button',
                    text: 'Nuevo',
                    iconCls: 'btnNuevoIcon',
                    itemId: 'btnNuevo',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnNuevo'
                },
                {
                    xtype: 'button',
                    text: 'Recargar',
                    iconCls: 'btnRecargarIcon',
                    itemId: 'btnRecargar',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnRecargar'
                },
                {
                    xtype: 'tbseparator'
                },
                {
                    xtype: 'tbfill'
                },
                {
                    xtype: 'button',
                    text: 'Ver Lista',
                    iconCls: 'btnVerLista_32_icon',
                    itemId: 'btnSVerLista',
                    scale: 'medium',
                    iconAlign: 'top',
                    ref: '../btnSVerLista'
                }
            ]
        };
        frmPendientesUi.superclass.initComponent.call(this);
    }
});
