/*
 * File: gridTareas.js
 * Date: Thu Sep 13 2012 22:12:24 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

gridTareas = Ext.extend(gridTareasUi, {
    initComponent: function() {
        gridTareas.superclass.initComponent.call(this);
    }
});
Ext.reg('gridTareas', gridTareas);