/*
 * File: gridUsuarios.js
 * Date: Sun Sep 09 2012 22:48:14 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

gridUsuarios = Ext.extend(gridUsuariosUi, {
    initComponent: function() {
        gridUsuarios.superclass.initComponent.call(this);
		this.store=new stoUsuarios({
			url: '/usuarios/listar',
			api:{
				read: '/usuarios/listar',
				create: '/usuarios/crear',
				update: '/usuarios/guardar',
				destroy: '/usuarios/eliminar'
			},
			writer:new Ext.data.JsonWriter({
				encode: true,
				writeAllFields: true // write all fields, not just those that changed
			})
		});
		this.bottomToolbar.bind(this.store);
		//----------------------------------
	//  para que este grid se comporte como un grid del catalogo crud, ejecutamos la siguiente linea
	
		Ext.apply(this,comportamiento_grid,{
			xtype_del_form:"usuarios_edicion"
		});	
		
	//  y asi se activa el comporstamiento
		this.activarComportamiento();
	//----------------------------------
		this.bottomToolbar.doRefresh();
}
});
Ext.reg('gridUsuarios', gridUsuarios);