/*
 * File: usuarios_edicion.ui.js
 * Date: Sun Sep 09 2012 23:24:26 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

usuarios_edicionUi = Ext.extend(Ext.form.FormPanel, {
    title: 'My Form',
    width: 400,
    height: 250,
    padding: 10,
    initComponent: function() {
        this.items = [
            {
                xtype: 'textfield',
                fieldLabel: 'Id',
                anchor: '100%',
                name: 'id',
                ref: 'txtId'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'email',
                anchor: '100%',
                name: 'email',
                vtype: 'email',
                ref: 'txtEmail'
            },
            {
                xtype: 'textfield',
                fieldLabel: 'Nombre Publico',
                anchor: '100%',
                name: 'nombre',
                ref: 'txtNomPub'
            },
            {
                xtype: 'button',
                text: 'Generar Contraseña',
                iconCls: 'btnGenerar_pass',
                style: 'float:right;'
            }
        ];
        this.tbar = {
            ref: 'tbCrud',
            xtype: 'crud16_toolbar'
        };
        usuarios_edicionUi.superclass.initComponent.call(this);
    }
});
