/*
 * File: usuarios_edicion.js
 * Date: Sun Sep 09 2012 18:47:00 GMT-0600 (Hora verano, Montañas (México))
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

usuarios_edicion = Ext.extend(usuarios_edicionUi, {
    initComponent: function() {
        usuarios_edicion.superclass.initComponent.call(this);
		this.controlador='usuarios';
		
		this.on("afterrender",function(){
			Ext.applyIf(this,comportamiento_formulario);		
			this.activarComportamiento();			
		},this);
		
    },
	actualizarTitulo:function(	action ){		
		if (action=="guardado" || action=="edicion")
			this.setTitle(this.txtEmail.getValue() );
	}
});
Ext.reg('usuarios_edicion', usuarios_edicion);